name: ink_flow_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutterflow_paginate_firestore: ^1.0.3+1
  google_sign_in: ^6.2.1
  signature: ^5.4.1
  toastification: ^1.2.1
  provider:
  flutter_slidable:
  image_picker:
  firebase_storage: ^11.6.9
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - lib/images/
