// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQvbNdeij77FIQ3LCihBraeMU_IiMk9Y',
    appId: '1:301488040485:android:746d5e829fa1c8dd8aadcc',
    messagingSenderId: '301488040485',
    projectId: 'ink-flow-manager',
    storageBucket: 'ink-flow-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpLgMoZtt5LDQsNV1rR5qFdQ-qvatCEE',
    appId: '1:301488040485:ios:629761e92ae8f2c28aadcc',
    messagingSenderId: '301488040485',
    projectId: 'ink-flow-manager',
    storageBucket: 'ink-flow-manager.appspot.com',
    androidClientId: '301488040485-tmhb3ddt55s3gbss736c08gucjrar0mh.apps.googleusercontent.com',
    iosClientId: '301488040485-igg89o6odqocltgeqpbf185c4ph67mte.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkFlowManager',
  );
}
